Feature/new datepicker
takenet/blip-ds pull request #251
Opened 2022-01-31 13:20 UTC by LucasMurtaTakeBlip

2022-01-31 15:15 UTC, WillianLomeu requested changes

2022-01-31 15:15 UTC, WillianLomeu commented on src/components/datepicker/datepicker.tsx
> +      console.error('Date field is not formatted correctly. Please enter with the example dd/mm/yyyy.');
Não publicar console.log na prod.

2022-01-31 15:15 UTC, WillianLomeu commented on src/components/datepicker/datepicker.tsx
> +      console.error('Date field is not formatted correctly. Please enter with the example dd/mm/yyyy.');
Não publicar console.log na prod.

2022-01-31 15:15 UTC, WillianLomeu commented on src/components/datepicker/datepicker.tsx
> +      console.error('The end date limit field is smaller than the start date.');
Não publicar console.log na prod.

2022-01-31 15:18 UTC, LucasMurtaTakeBlip commented on src/components/datepicker/datepicker.tsx
> +      console.error('Date field is not formatted correctly. Please enter with the example dd/mm/yyyy.');
esse console é de erro, pra noticar que o formato da data não esta correto.

2022-01-31 15:18 UTC, LucasMurtaTakeBlip commented on src/components/datepicker/datepicker.tsx
> +      console.error('Date field is not formatted correctly. Please enter with the example dd/mm/yyyy.');
esse console é de erro, pra noticar que o formato da data não esta correto.

2022-02-02 13:35 UTC, WillianLomeu requested changes

2022-02-02 13:35 UTC, WillianLomeu commented on src/index.html
> +    <bds-datepicker type-of-date="single" message="Selecione no máximo 30 dias"></bds-datepicker>
Apagar qualquer conteúdo do body para prod.

2022-02-02 13:51 UTC, WillianLomeu approved these changes

2022-02-02 14:04 UTC, merged